### ISSUE TITLE
关于“ModuleNotFoundError: No module named 'bert_base.train'”报错

### ISSUE THREAD

**Issue by atomliang** [yanwii/ChineseNER#10]
Traceback (most recent call last):
  File "model.py", line 13, in <module>
    from bert_base.train import tf_metrics
ModuleNotFoundError: No module named 'bert_base.train'
请问是不是缺少什么文件啊

**Comment by yanwii** [comment]
没装bert？
```
pip install bert_base
```

**Comment by atomliang** [comment]
谢谢，问题已解决
