### ISSUE TITLE
请教：如果想训练其他实体类别，需要在data_utils里增加tag_map吗？还是只要在训练数据里增加就可以？

### ISSUE THREAD

**Issue by muzier** [yanwii/ChineseNER#14]
请教大神：如果想训练其他实体类别，需要在data_utils里增加tag_map吗？还是只要在训练数据里增加就可以？
我看在 data_utils 的 DataBatch 类下面有一行 tag_map 被注掉了，是不是需要在这里增加其他实体的类别才能识别出来呢？
先谢过啦

**Comment by yanwii** [comment]
在语料里添加就行了，读取时会自动加到tag_map里面
