### ISSUE TITLE
是必须要启用GPU才能跑吗？

### ISSUE THREAD

**Issue by jinpeijie217** [yanwii/ChineseNER#5]
InvalidArgumentError (see above for traceback): Cannot assign a device for operation init: node init (defined at model.py:323) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.
	 [[node init (defined at model.py:323) ]]

**Comment by yanwii** [comment]
你可以设置为在cpu上跑
