### ISSUE TITLE
请问model.py 356行左右的代码是什么意思

### ISSUE THREAD

**Issue by zdx1012** [yanwii/ChineseNER#6]
self.bert_evaluate(sess, "ORG")
                        self.bert_evaluate(sess, "PER")

如果我想识别出时间、地名等信息，除了改标注信息，这里要改动吗

**Comment by yanwii** [comment]
这里只是用来验证某个标签的召回、准确率，可以改成你的标签

**Comment by zdx1012** [comment]
好的，感谢！
