### ISSUE TITLE
batch_size及训练速度问题

### ISSUE THREAD

**Issue by thupx** [yanwii/ChineseNER#8]
在实际运行代码的过程中，发现batch_size设置为8时就会OOM，使用的是1080Ti显卡，11G显存。请问这种情况是否正常？
如果batch_size只能设置成这么小，训练过程会非常缓慢，1.5w数据的话，一个epoch需要40分钟左右，这个训练速度也是正常的吗？请问有什么可以提速的方法吗？
谢谢~

**Comment by yanwii** [comment]
请问你使用的是bert模型吗，如果是还是比较正常的，如果想继续优化，可以从训练数据加载的方向切入，至于bert那部分，我们没办法进行优化。

**Comment by thupx** [comment]
> 请问你使用的是bert模型吗，如果是还是比较正常的，如果想继续优化，可以从训练数据加载的方向切入，至于bert那部分，我们没办法进行优化。

是的，我忘说了，用的就是BERT的模型。发现单卡跑起来比较费劲，而且发现从效果上来说还略差于用预训练的word2vec的模型，可能是我改写代码的问题。
不过项目文件结构清晰，代码也很简明，赞！
