### ISSUE TITLE
预测时出现首个字符被标记为cls的问题

### ISSUE THREAD

**Issue by zdx1012** [yanwii/ChineseNER#9]
![QAP5W2H481`JK8N$E650S@Y](https://user-images.githubusercontent.com/23023879/60253489-d2f69000-98fe-11e9-808c-66dae92b0523.png)
![RQYW666`BZH 0 UT6FDY1NH](https://user-images.githubusercontent.com/23023879/60253490-d2f69000-98fe-11e9-8455-d1759c58cd4e.png)

大佬，这个是什么导致的呢，我该怎么改

**Comment by thupx** [comment]
预测的时候在句子首尾分别加上[CLS]，[SEP]即可。

**Comment by zdx1012** [comment]
我应该把原字符串改成
[CLS]2019女青年应征报名时间[SEP]
吗？

**Comment by thupx** [comment]
是的，这样预测出来的也是
[CLS] XXXXXX [SEP]
取解码序列的[1: -1]即可

**Comment by zdx1012** [comment]
我现在在prepare_bert_pred_data这个方法里，添加了[CLS] 和 [SEP]，然后model.py 486行对出来的数据进行了切片，就可以解决这个问题了。
这个模型的超参数，是只有helper.py中的那些吗？
是只有学习率可以调整吗?

**Comment by fanruifeng** [comment]
大佬们, 我也遇到这个问题了,请问你们怎么解决的呢, 是在模型预测前进行的处理？

**Comment by fanruifeng** [comment]
> 我现在在prepare_bert_pred_data这个方法里，添加了[CLS] 和 [SEP]，然后model.py 486行对出来的数据进行了切片，就可以解决这个问题了。
> 这个模型的超参数，是只有helper.py中的那些吗？
> 是只有学习率可以调整吗?
大佬, 你在prepare_bert_pred_data这个方法里 怎么添加的[CLS] 和 [SEP]

**Comment by zdx1012** [comment]
![image](https://user-images.githubusercontent.com/23023879/65218133-68fa1b00-dae8-11e9-8c53-90021ea80ed5.png)
![image](https://user-images.githubusercontent.com/23023879/65218168-7e6f4500-dae8-11e9-97fc-61a9f184061d.png)
我以前这样做的，不知道对不对，后面都没跑过了，你测试一下，看行不行

**Comment by zdx1012** [comment]
@fanruifeng

**Comment by fanruifeng** [comment]
> @fanruifeng

好的  谢谢 解决了
